2021-10-28 10:43:04.608726: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/cuda-10.1-el7-x86_64/extras/CUPTI/lib64:/software/cuda-10.1-el7-x86_64/lib64:/software/slurm-current-el7-x86_64/lib64:/software/slurm-current-el7-x86_64/lib:/software/python-anaconda-2020.02-el7-x86_64/lib:/software/git-2.10-el7-x86_64/lib64:/software/subversion-1.9.4-el7-x86_64/lib:/software/serf-1.3.9-el7-x86_64/lib
2021-10-28 10:43:04.610388: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-28 10:43:04.610483: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dali004.rcc.local): /proc/driver/nvidia/version does not exist
2021-10-28 10:43:04.627849: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2021-10-28 10:43:04.991939: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2021-10-28 10:43:04.996441: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55769d7fd400 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-10-28 10:43:04.996549: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-10-28 10:43:18.258761: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2021-10-28 10:43:18.747465: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.1
2021-10-28 10:43:18.872336: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-28 10:43:18.873429: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1355] function cupti_interface_->ActivityEnable(activity)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-28 10:43:26.060052: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2021-10-28 10:43:26.061992: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
Traceback (most recent call last):
  File "neural_main.py", line 44, in <module>
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "/project2/nicho/weiliang/videoNet/code/train.py", line 62, in train
    sessions,monkey,array,seed,lfp_start_ms,lfp_end_ms)
  File "/project2/nicho/weiliang/videoNet/code/video_supportive.py", line 31, in readAndDivideData
    f = h5py.File(filepath,'r')
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/tf-gpu-2.1-cuda-10.1/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/tf-gpu-2.1-cuda-10.1/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
